spring:
  data:
    mongodb:
      uri: mongodb://root:123@localhost:27017/chat_app?authSource=admin
      username: root
      password: 123
      host: localhost
      port: 27017
      database: chat_app
      authentication-database: admin
server:
  port: 8088
  host: 0.0.0.0
